services:
  web:
    build: .
    container_name: restaurant_web
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            gunicorn restaurant_site.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./restaurant_site:/restaurant_site
      - ./restaurant_site/media:/restaurant_site/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: restaurant_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: