# Generated by Django 4.2.30 on 2026-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sync_is_staff_from_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'користувач', 'verbose_name_plural': 'користувачі'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Клієнт'), ('staff', 'Персонал'), ('admin', 'Адміністратор ресторану')], default='customer', help_text='Клієнт — лише замовлення. Персонал і адміністратор — панель замовлень. Доступ до цієї Django-admin синхронізується з роллю автоматично.', max_length=20, verbose_name='Роль на сайті'),
        ),
    ]
