# Generated by Django 4.2.30 on 2026-05-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_catalog_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_gluten_free',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_lactose_free',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_nut_free',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vegan',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vegetarian',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_gluten_free',
            field=models.BooleanField(default=True, verbose_name='Без глютену'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_lactose_free',
            field=models.BooleanField(default=True, verbose_name='Без лактози'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_nut_free',
            field=models.BooleanField(default=True, verbose_name='Без горіхів'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_vegan',
            field=models.BooleanField(default=True, verbose_name='Веганське'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_vegetarian',
            field=models.BooleanField(default=True, verbose_name='Вегетаріанське'),
        ),
    ]
