# Generated by Django 4.2.30 on 2026-05-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_is_gluten_free_dish_is_lactose_free_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemRemovedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_ingredients', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemRemovedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_ingredients', to='orders.cartitem')),
            ],
        ),
    ]
