# Generated by Django 4.2.30 on 2026-05-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_ingredient_price'),
        ('orders', '0002_orderitemremovedingredient_cartitemremovedingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemAddedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_ingredients', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemAddedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_ingredients', to='orders.cartitem')),
            ],
        ),
    ]
