# Generated by Django 4.2.30 on 2026-05-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitemremovedingredient_cartitemremovedingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
